# Generated by Django 3.0.4 on 2020-03-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shockinfo',
            name='ct',
            field=models.CharField(default=673.3333333333334, max_length=200),
        ),
        migrations.AddField(
            model_name='shockinfo',
            name='currcapital',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='shockinfo',
            name='listing_date',
            field=models.CharField(default=673.3333333333334, max_length=200),
        ),
        migrations.AddField(
            model_name='shockinfo',
            name='maket',
            field=models.CharField(default='sz', max_length=200),
        ),
        migrations.AddField(
            model_name='shockinfo',
            name='mgjzc',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='shockinfo',
            name='profit_four',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='shockinfo',
            name='state',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='shockinfo',
            name='totalcapital',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
