# Generated by Django 3.0.4 on 2020-03-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shock', '0003_auto_20200327_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShockInfo',
        ),
    ]
