# Generated by Django 3.0.4 on 2020-03-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shock', '0006_auto_20200328_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='shock_trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('num', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shock.User')),
            ],
        ),
    ]
