# Generated by Django 3.0.4 on 2020-03-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shock', '0009_auto_20200328_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='shock_trade',
            name='code_str',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='shock_trade',
            name='cost',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
