# Generated by Django 3.0.4 on 2020-03-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shock', '0010_auto_20200329_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='shock_trade',
            name='now_price',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='shock_trade',
            name='profit',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
