# Generated by Django 3.0.4 on 2020-03-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shock', '0014_auto_20200329_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shock_trade',
            name='now_price',
            field=models.FloatField(default=0),
        ),
    ]
